import { Component, OnInit } from '@angular/core';
import { Router, ActivatedRoute } from '@angular/router';
import { getAllorders, IdProducts } from 'Api/services/entities_manager/indexEntitiesManager';

type TrackingStatus = 'done' | 'current' | 'pending';

interface TrackingStep {
  date: string;
  time: string;
  title: string;
  address: string;
  status: TrackingStatus;
}

interface TrackingInfo {
  shippingId: string;
  steps: TrackingStep[];
}

interface OrderDetail {
  id: string;
  imageUrl: string;
  title: string;
  link: string;
  description: string;
}

@Component({
  selector: 'app-trackorder',
  templateUrl: './trackorder.page.html',
  styleUrls: ['./trackorder.page.scss'],
  standalone: false,
})
export class TrackorderPage implements OnInit {

  darkMode = false;

  trackingInfo: TrackingInfo | null = null;
  orderDetails: OrderDetail | null = null;

  constructor(
    private router: Router,
    private route: ActivatedRoute
  ) { }

  ngOnInit(): void {
    this.checkAppMode();

    const id = this.route.snapshot.paramMap.get("id");

    if (!id) {
      this.router.navigateByUrl('/tabs/history');
      return;
    }

    this.loadOrderInfo(id);      // <-- 🔥 carga título, imagen, descripción
    this.loadTrackingById(id);   // <-- tracking
  }

  async loadOrderInfo(orderId: string) {
    try {
      const resp: any = await IdProducts(orderId);

      const found = resp.data;
      console.log("ORDER:", found);

      this.orderDetails = {
        id: found.id,
        title: found.title,
        description: found.description,
        link: found.url,
        imageUrl: found.image   // <-- aquí está la imagen real
      };


    } catch (e) {
      console.error("Error loading product info:", e);
    }
  }

  loadTrackingById(shippingId: string) {

    const backendStatus: "Pending" | "Completed" = "Pending";

    const mapBackendToTracking = (status: "Pending" | "Completed"): TrackingStatus => {
      switch (status) {
        case "Pending":
          return "current";
        case "Completed":
          return "done";
        default:
          return "pending";
      }
    };

    const convertedStatus: TrackingStatus = mapBackendToTracking(backendStatus);

    this.trackingInfo = {
      shippingId,
      steps: [
        {
          date: 'Today',
          time: '12:50',
          title: 'Package has been received',
          address: 'System autogenerated',
          status: convertedStatus,
        },
        {
          date: 'Today',
          time: '13:00',
          title: 'Accept by Wedx',
          address: 'System autogenerated',
          status: convertedStatus === 'done' ? 'done' : 'pending',
        },
      ]
    };
  }

  goBack() {
    this.router.navigateByUrl('/tabs/history');
  }

  async checkAppMode() {
    const checkIsDarkMode = localStorage.getItem('darkModeActivated');
    this.darkMode = checkIsDarkMode === 'true';
    document.body.classList.toggle('dark', this.darkMode);
  }
}
